[package]
edition = "2021"
name = "tauri-ipc-macros"
version = "0.1.2"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.71", features = ["full"] }
